import type { Product, Vehicle } from './types';

export const products: Product[] = [
  {
    id: 'e36-bomba-freno',
    name: 'Bomba de Freno para BMW E36',
    sku: 'E36-BF-001',
    category: 'Original',
    price: 100000,
    description: 'Bomba de freno de alta precisión para BMW E36. Garantiza presión hidráulica estable y mejora la respuesta del pedal de freno. Ideal para reemplazo de piezas desgastadas.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/bomba-freno/500/500'],
  },
  {
    id: 'e36-booster',
    name: 'Booster (Servofreno) para BMW E36',
    sku: 'E36-BST-001',
    category: 'Original',
    price: 100000,
    description: 'Asistencia de frenado eficiente. Reduce el esfuerzo al frenar. Instalación directa tipo OEM. Compatible con sistema original BMW.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/booster/500/500'],
  },
  {
    id: 'e36-bomba-agua',
    name: 'Bomba de Agua para BMW E36',
    sku: 'E36-BA-001',
    category: 'Original',
    price: 100000,
    description: 'Mantiene la circulación adecuada del refrigerante. Ayuda a prevenir sobrecalentamiento del motor. Construcción resistente para larga duración. Ajuste directo para BMW E36.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/bomba-agua/500/500'],
  },
  {
    id: 'e36-volante',
    name: 'Volante para BMW E36',
    sku: 'E36-VOL-001',
    category: 'Original',
    price: 100000,
    description: 'Diseño ergonómico, compatible con sistema de dirección BMW E36. Mejora el control y la conducción. Opciones originales o deportivas.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/volante/500/500'],
  },
  {
    id: 'e36-computadora',
    name: 'Computadora (DME) para BMW E36',
    sku: 'E36-ECU-001',
    category: 'Original',
    price: 100000,
    description: 'Computadora de motor (DME) para BMW E36. Restaura el rendimiento original y la gestión electrónica de tu vehículo.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/computadora/500/500'],
  },
  {
    id: 'e36-compensadores',
    name: 'Compensadores para BMW E36',
    sku: 'E36-CMP-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Ayudan a mantener balance en el sistema mecánico. Ofrecen un funcionamiento suave y preciso. Compatible con componentes originales.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/compensadores/500/500'],
  },
  {
    id: 'e36-discos-freno',
    name: 'Discos de Freno para BMW E36',
    sku: 'E36-DF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Alta resistencia al calor y excelente rendimiento de frenado. Material duradero y confiable, compatible con sistema original del E36.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/discos-freno/500/500'],
  },
  {
    id: 'e36-roles-empuje',
    name: 'Roles de Empuje para BMW E36',
    sku: 'E36-RE-001',
    category: 'Original',
    price: 100000,
    description: 'Reduce fricción en componentes móviles. Mejora funcionamiento del sistema. Material resistente al desgaste.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/roles-empuje/500/500'],
  },
  {
    id: 'e36-consola-central',
    name: 'Consola Central para BMW E36',
    sku: 'E36-CC-001',
    category: 'Original',
    price: 100000,
    description: 'Plástico original o de alta calidad. Ajuste perfecto al interior del E36. Mejora la estética del vehículo. Fácil instalación.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/consola-central/500/500'],
  },
  {
    id: 'e36-bomba-gasolina',
    name: 'Bomba de Gasolina para BMW E36',
    sku: 'E36-BG-001',
    category: 'Original',
    price: 100000,
    description: 'Flujo constante de combustible. Mejora el rendimiento del motor. Compatible con sistema original. Alta durabilidad.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/bomba-gasolina/500/500'],
  },
  {
    id: 'e36-cluster',
    name: 'Cluster (Panel de Instrumentos) para BMW E36',
    sku: 'E36-CLU-001',
    category: 'Usado',
    price: 100000,
    description: 'Lectura clara de velocidad, RPM y combustible. Compatible con sistema eléctrico original. Ideal para reemplazo o restauración.',
    stock: 10,
    condition: 'Usado',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/cluster/500/500'],
  },
  {
    id: 'e36-resortes',
    name: 'Resortes de Suspensión para BMW E36',
    sku: 'E36-RES-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Mantienen la altura correcta del vehículo. Mejoran estabilidad y manejo. Construcción en acero de alta resistencia.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/resortes/500/500'],
  },
  {
    id: 'e36-espejos',
    name: 'Espejos Retrovisores para BMW E36',
    sku: 'E36-ESP-001',
    category: 'Original',
    price: 100000,
    description: 'Diseño original para BMW E36. Excelente visibilidad y ajuste preciso en carrocería. Construcción resistente.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/espejos/500/500'],
  },
  {
    id: 'e36-dash',
    name: 'Dash (Tablero) para BMW E36',
    sku: 'E36-DSH-001',
    category: 'Original',
    price: 100000,
    description: 'Diseño original BMW. Mejora apariencia interior. Material resistente al calor y desgaste. Ideal para restauraciones.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/dash/500/500'],
  },
  {
    id: 'e36-asientos',
    name: 'Asientos para BMW E36',
    sku: 'E36-ASN-001',
    category: 'Usado',
    price: 100000,
    description: 'Comodidad y soporte ergonómico. Compatibles con rieles originales. Perfectos para restauración o reemplazo.',
    stock: 10,
    condition: 'Usado',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/asientos/500/500'],
  },
  {
    id: 'e34-bomba-agua',
    name: 'Bomba de Agua para BMW E34',
    sku: 'E34-BA-001',
    category: 'Original',
    price: 100000,
    description: 'Asegura la óptima circulación del refrigerante en tu BMW E34 para prevenir el sobrecalentamiento. Pieza de reemplazo directo de alta calidad.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-bomba-agua/500/500']
  },
  {
    id: 'e34-termostato',
    name: 'Termostato para BMW E34',
    sku: 'E34-TRM-001',
    category: 'Original',
    price: 100000,
    description: 'Regula la temperatura del motor de tu E34, garantizando un rendimiento eficiente y protegiendo contra el desgaste prematuro.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-termostato/500/500']
  },
  {
    id: 'e34-radiador',
    name: 'Radiador para BMW E34',
    sku: 'E34-RAD-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Disipa el calor del motor de manera efectiva. Fabricado con materiales de alta calidad para una máxima durabilidad en tu BMW E34.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-radiador/500/500']
  },
  {
    id: 'e34-bujias',
    name: 'Juego de Bujías para BMW E34',
    sku: 'E34-BUJ-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Mejora la ignición y la eficiencia del combustible. Juego de bujías de alto rendimiento para motores de BMW E34.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-bujias/500/500']
  },
  {
    id: 'e34-amortiguadores',
    name: 'Juego de Amortiguadores para BMW E34',
    sku: 'E34-AMT-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Restaura la comodidad y estabilidad de la conducción de tu E34. Amortiguadores de alta calidad para un manejo suave y seguro.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-amortiguadores/500/500']
  },
  {
    id: 'e34-pastillas-freno',
    name: 'Pastillas de Freno para BMW E34',
    sku: 'E34-PF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Potencia de frenado confiable y bajo nivel de ruido. Compuesto de alta calidad para un rendimiento superior en tu BMW E34.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-pastillas-freno/500/500']
  },
  {
    id: 'e34-discos-freno',
    name: 'Discos de Freno Delanteros para BMW E34',
    sku: 'E34-DF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Discos de freno ventilados para una disipación de calor superior y un rendimiento de frenado constante en tu BMW E34.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-discos-freno/500/500']
  },
  {
    id: 'e34-brazo-suspension',
    name: 'Brazo de Suspensión para BMW E34',
    sku: 'E34-BS-001',
    category: 'Original',
    price: 100000,
    description: 'Componente clave para la estabilidad y el manejo. Reemplazo directo para restaurar la geometría de la suspensión de tu E34.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-brazo-suspension/500/500']
  },
  {
    id: 'e34-filtro-aceite',
    name: 'Filtro de Aceite para BMW E34',
    sku: 'E34-FA-001',
    category: 'Original',
    price: 100000,
    description: 'Protege tu motor con un filtrado de aceite eficiente. Diseñado para cumplir con las especificaciones OEM para el BMW E34.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-filtro-aceite/500/500']
  },
  {
    id: 'e34-alternador',
    name: 'Alternador para BMW E34',
    sku: 'E34-ALT-001',
    category: 'Original',
    price: 100000,
    description: 'Garantiza un suministro de energía estable para el sistema eléctrico de tu E34. Reemplazo de alta calidad para una máxima fiabilidad.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E34'],
    imageUrls: ['https://picsum.photos/seed/e34-alternador/500/500']
  },
  {
    id: 'e30-bomba-agua',
    name: 'Bomba de Agua para BMW E30',
    sku: 'E30-BA-001',
    category: 'Original',
    price: 100000,
    description: 'Esencial para el sistema de enfriamiento de tu BMW E30. Asegura una circulación óptima del refrigerante para mantener la temperatura del motor bajo control.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-bomba-agua/500/500'],
  },
  {
    id: 'e30-correa-distribucion',
    name: 'Correa de Distribución para BMW E30',
    sku: 'E30-CD-001',
    category: 'Original',
    price: 100000,
    description: 'Correa de distribución de alta resistencia para BMW E30. Sincroniza el cigüeñal y el árbol de levas para un funcionamiento preciso del motor.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-correa-distribucion/500/500'],
  },
  {
    id: 'e30-termostato',
    name: 'Termostato para BMW E30',
    sku: 'E30-TRM-001',
    category: 'Original',
    price: 100000,
    description: 'Regula la temperatura del motor de tu E30, permitiendo un calentamiento rápido y manteniendo la temperatura de funcionamiento ideal.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-termostato/500/500'],
  },
  {
    id: 'e30-bujias',
    name: 'Juego de Bujías para BMW E30',
    sku: 'E30-BUJ-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Mejora el arranque y la eficiencia del combustible con este juego de bujías de alto rendimiento, diseñadas para el BMW E30.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-bujias/500/500'],
  },
  {
    id: 'e30-amortiguadores',
    name: 'Juego de Amortiguadores para BMW E30',
    sku: 'E30-AMT-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Devuelve la estabilidad y el confort a tu BMW E30. Este juego de amortiguadores mejora el control del vehículo y absorbe las irregularidades del camino.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-amortiguadores/500/500'],
  },
  {
    id: 'e30-pastillas-freno',
    name: 'Pastillas de Freno para BMW E30',
    sku: 'E30-PF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Pastillas de freno con compuesto de alta fricción para una frenada segura y eficaz en tu BMW E30. Reducen el ruido y el polvo.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-pastillas-freno/500/500'],
  },
  {
    id: 'e30-discos-freno',
    name: 'Discos de Freno para BMW E30',
    sku: 'E30-DF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Discos de freno de alta durabilidad para BMW E30. Diseñados para una disipación de calor óptima y un rendimiento de frenado consistente.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-discos-freno/500/500'],
  },
  {
    id: 'e30-bujes-suspension',
    name: 'Bujes de Suspensión para BMW E30',
    sku: 'E30-BS-001',
    category: 'Original',
    price: 100000,
    description: 'Restaura la precisión de la dirección y reduce las vibraciones con estos bujes de suspensión de alta calidad para tu BMW E30.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-bujes-suspension/500/500'],
  },
  {
    id: 'e30-filtro-combustible',
    name: 'Filtro de Combustible para BMW E30',
    sku: 'E30-FC-001',
    category: 'Original',
    price: 100000,
    description: 'Protege el sistema de inyección de tu BMW E30 de impurezas. Un filtro de combustible limpio es clave para el rendimiento del motor.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-filtro-combustible/500/500'],
  },
  {
    id: 'e30-alternador',
    name: 'Alternador para BMW E30',
    sku: 'E30-ALT-001',
    category: 'Original',
    price: 100000,
    description: 'Asegura una carga constante de la batería y alimenta el sistema eléctrico de tu BMW E30 con este alternador de reemplazo fiable.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E30'],
    imageUrls: ['https://picsum.photos/seed/e30-alternador/500/500'],
  },
  {
    id: 'e21-bomba-agua',
    name: 'Bomba de Agua para BMW E21',
    sku: 'E21-BA-001',
    category: 'Original',
    price: 100000,
    description: 'Bomba de agua de alta calidad para BMW E21. Esencial para mantener el sistema de enfriamiento de tu motor funcionando de manera óptima.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-bomba-agua/500/500']
  },
  {
    id: 'e21-termostato',
    name: 'Termostato para BMW E21',
    sku: 'E21-TRM-001',
    category: 'Original',
    price: 100000,
    description: 'Termostato de reemplazo para BMW E21. Ayuda a regular la temperatura del motor para un rendimiento y eficiencia ideales.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-termostato/500/500']
  },
  {
    id: 'e21-bujias',
    name: 'Juego de Bujías para BMW E21',
    sku: 'E21-BUJ-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Juego de bujías de alto rendimiento para BMW E21. Mejora la combustión, el arranque y la eficiencia del combustible.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-bujias/500/500']
  },
  {
    id: 'e21-amortiguadores',
    name: 'Juego de Amortiguadores para BMW E21',
    sku: 'E21-AMT-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Amortiguadores de calidad para BMW E21 que restauran la estabilidad, el control y la comodidad de la conducción original.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-amortiguadores/500/500']
  },
  {
    id: 'e21-pastillas-freno',
    name: 'Pastillas de Freno para BMW E21',
    sku: 'E21-PF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Pastillas de freno diseñadas para ofrecer una frenada segura y consistente para tu BMW E21, con bajo nivel de ruido y polvo.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-pastillas-freno/500/500']
  },
  {
    id: 'e21-discos-freno',
    name: 'Discos de Freno para BMW E21',
    sku: 'E21-DF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Discos de freno para BMW E21 fabricados con materiales de alta calidad para una excelente disipación del calor y durabilidad.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-discos-freno/500/500']
  },
  {
    id: 'e21-bujes-suspension',
    name: 'Bujes de Suspensión para BMW E21',
    sku: 'E21-BS-001',
    category: 'Original',
    price: 100000,
    description: 'Restaura la precisión de la dirección y elimina ruidos en la suspensión de tu BMW E21 con este juego de bujes de alta calidad.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-bujes-suspension/500/500']
  },
  {
    id: 'e21-filtro-aceite',
    name: 'Filtro de Aceite para BMW E21',
    sku: 'E21-FA-001',
    category: 'Original',
    price: 100000,
    description: 'Filtro de aceite OEM para BMW E21. Protege tu motor de impurezas y asegura una lubricación óptima.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-filtro-aceite/500/500']
  },
  {
    id: 'e21-alternador',
    name: 'Alternador para BMW E21',
    sku: 'E21-ALT-001',
    category: 'Original',
    price: 100000,
    description: 'Alternador de reemplazo para BMW E21. Garantiza la carga correcta de la batería y el funcionamiento de todo el sistema eléctrico.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-alternador/500/500']
  },
  {
    id: 'e21-radiador',
    name: 'Radiador para BMW E21',
    sku: 'E21-RAD-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Radiador de alta eficiencia para BMW E21. Mejora la capacidad de enfriamiento del motor y previene el sobrecalentamiento.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E21'],
    imageUrls: ['https://picsum.photos/seed/e21-radiador/500/500']
  }
];

export const vehicles: Vehicle[] = [
  {
    id: 'dodge-ram-1500',
    make: 'Dodge',
    model: 'RAM 1500',
    year: 2022,
    price: 25000000,
    mileage: 30000,
    vin: 'VINRAM1500',
    engine: '5.7L V8',
    transmission: 'Automático',
    exteriorColor: 'Gris',
    interiorColor: 'Negro',
    features: ['Pantalla Táctil', '4x4', 'Cámara de Reversa'],
    description: 'Potente y lujoso pickup Dodge RAM 1500. Ideal para trabajo y aventura.',
    imageUrls: [
      'https://picsum.photos/seed/dodge-ram-cover/600/400',
      'https://picsum.photos/seed/ram-2/600/400',
      'https://picsum.photos/seed/ram-3/600/400',
      'https://picsum.photos/seed/ram-4/600/400'
    ],
    availabilityStatus: 'Available',
  },
  {
    id: 'subaru-impreza-wrx',
    make: 'Subaru',
    model: 'Impreza WRX',
    year: 2020,
    price: 22000000,
    mileage: 45000,
    vin: 'VINSUBARUWRX',
    engine: '2.0L Turbo',
    transmission: 'Manual',
    exteriorColor: 'Azul',
    interiorColor: 'Negro',
    features: ['AWD', 'Turbo', 'Asientos Deportivos'],
    description: 'Icónico Subaru Impreza WRX. Rendimiento y tracción integral legendarios.',
    imageUrls: ['https://picsum.photos/seed/wrx-1/600/400'],
    availabilityStatus: 'Available',
  },
  {
    id: 'chevrolet-tracker',
    make: 'Chevrolet',
    model: 'Tracker',
    year: 2021,
    price: 15000000,
    mileage: 25000,
    vin: 'VINCHEVYTRACKER',
    engine: '1.2L Turbo',
    transmission: 'Automático',
    exteriorColor: 'Rojo',
    interiorColor: 'Gris',
    features: ['SUV Compacto', 'Techo Panorámico', 'Pantalla MyLink'],
    description: 'Moderno y eficiente SUV Chevrolet Tracker. Perfecto para la ciudad.',
    imageUrls: ['https://picsum.photos/seed/tracker-1/600/400'],
    availabilityStatus: 'Available',
  },
  {
    id: 'bmw-e46-venta',
    make: 'BMW',
    model: 'E46',
    year: 2004,
    price: 8000000,
    mileage: 150000,
    vin: 'VINBMWE46VENTA',
    engine: '2.5L 6-cil',
    transmission: 'Manual',
    exteriorColor: 'Plata',
    interiorColor: 'Negro',
    features: ['Paquete M', 'Sunroof', 'Asientos de cuero'],
    description: 'Clásico y deportivo BMW E46. Una experiencia de manejo pura.',
    imageUrls: ['https://picsum.photos/seed/e46-1/600/400'],
    availabilityStatus: 'Available',
  },
];
