import type { Product, Vehicle } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'BMW M Performance Kidney Grille in High-Gloss Black',
    category: 'Original',
    price: 95000,
    description: 'Enhance the sporty look of your BMW with this original M Performance kidney grille. Made from high-quality, durable plastic with a high-gloss black finish.',
    stock: 15,
    condition: 'Nuevo',
    compatibility: ['G20 3 Series', 'G22 4 Series'],
    imageUrls: ['https://picsum.photos/seed/grille/500/500', 'https://picsum.photos/seed/grille2/500/500'],
    isFeatured: true,
    discountPercentage: 10,
  },
  {
    id: 'p2',
    name: 'BBS CI-R 20" Performance Wheels (Set of 4)',
    category: 'Aftermarket',
    price: 1250000,
    description: 'Legendary BBS performance and style. The CI-R features a distinctive Y-spoke design and weight optimization for superior handling.',
    stock: 5,
    condition: 'Nuevo',
    compatibility: ['F80 M3', 'F82 M4', 'F10 5 Series'],
    imageUrls: ['https://picsum.photos/seed/wheel/500/500'],
    isFeatured: true,
  },
  {
    id: 'p3',
    name: 'Original BMW Oil Filter Kit',
    category: 'Original',
    price: 13500,
    description: 'Genuine BMW oil filter kit for various models. Includes filter, gasket, and necessary o-rings for a complete oil change service.',
    stock: 100,
    condition: 'Nuevo',
    compatibility: ['Most E-chassis and F-chassis models'],
    imageUrls: ['https://picsum.photos/seed/oilfilter/500/500'],
    isFeatured: true,
  },
  {
    id: 'p4',
    name: 'Akrapovič Slip-On Line (Titanium) Exhaust System',
    category: 'Aftermarket',
    price: 2350000,
    description: 'Unleash the sound and performance of your M car. This lightweight titanium exhaust system provides a power boost and an aggressive, deep tone.',
    stock: 3,
    condition: 'Nuevo',
    compatibility: ['F87 M2 Competition'],
    imageUrls: ['https://picsum.photos/seed/exhaust/500/500', 'https://picsum.photos/seed/exhaust2/500/500', 'https://picsum.photos/seed/exhaust3/500/500'],
    isFeatured: true,
    discountPercentage: 5,
  },
   {
    id: 'p5',
    name: 'BMW M Performance Carbon Fiber Mirror Caps',
    category: 'Original',
    price: 380000,
    description: 'Add a touch of race-inspired styling with these genuine carbon fiber mirror caps. Perfect fit and finish as expected from BMW M Performance.',
    stock: 8,
    condition: 'Nuevo',
    compatibility: ['G80 M3', 'G82 M4'],
    imageUrls: ['https://picsum.photos/seed/mirrorcap/500/500'],
    isFeatured: false,
  },
  {
    id: 'p6',
    name: 'Zimmermann Performance Brake Rotors (Front Pair)',
    category: 'Aftermarket',
    price: 165000,
    description: 'High-quality German-made brake rotors. Cross-drilled for improved heat dissipation and wet-weather performance. A popular OEM-alternative.',
    stock: 20,
    condition: 'Nuevo',
    compatibility: ['E90 335i', 'E92 335i'],
    imageUrls: ['https://picsum.photos/seed/brakerotor/500/500'],
    isFeatured: false,
  },
  {
    id: 'p7',
    name: 'BMW M Performance Alcantara Steering Wheel',
    category: 'Original',
    price: 490000,
    description: 'Upgrade your driving experience with this ergonomic Alcantara-wrapped steering wheel, featuring a red 12 o\'clock marker.',
    stock: 7,
    condition: 'Nuevo',
    compatibility: ['F22 2 Series', 'F30 3 Series'],
    imageUrls: ['https://picsum.photos/seed/steeringwheel/500/500'],
    isFeatured: false,
  },
  {
    id: 'p8',
    name: 'KW V3 Coilover Suspension Kit',
    category: 'Aftermarket',
    price: 1450000,
    description: 'State-of-the-art suspension technology for performance-oriented drivers. Independently adjustable rebound and compression damping.',
    stock: 4,
    condition: 'Nuevo',
    compatibility: ['F80 M3', 'F82 M4'],
    imageUrls: ['https://picsum.photos/seed/suspension/500/500'],
    isFeatured: false,
  },
];

export const vehicles: Vehicle[] = [
  {
    id: 'v1',
    make: 'BMW',
    model: 'M4 Competition',
    year: 2022,
    price: 44000000,
    mileage: 20116,
    vin: 'WBS123...',
    engine: '3.0L Twin-Turbo I6',
    transmission: 'Automático',
    exteriorColor: 'Isle of Man Green',
    interiorColor: 'Kyalami Orange',
    features: ['Carbon Fiber Roof', 'M-Sport Seats', 'Harman Kardon Sound', 'Executive Package'],
    description: 'A stunning, low-mileage example of the G82 M4 Competition. This vehicle is in immaculate condition and comes with a full service history.',
    imageUrls: ['https://picsum.photos/seed/greenm4/600/400', 'https://picsum.photos/seed/m4interior/600/400', 'https://picsum.photos/seed/m4wheel/600/400'],
    isFeatured: true,
  },
  {
    id: 'v2',
    make: 'BMW',
    model: 'X5 M50i',
    year: 2021,
    price: 37500000,
    mileage: 33796,
    vin: 'WBS456...',
    engine: '4.4L Twin-Turbo V8',
    transmission: 'Automático',
    exteriorColor: 'Carbon Black Metallic',
    interiorColor: 'Black Vernasca Leather',
    features: ['Driving Assistance Pro', 'Panoramic Sunroof', '22" M Wheels', 'Parking Assistance Package'],
    description: 'The perfect blend of luxury and performance. This X5 M50i offers thrilling power and ultimate comfort for the whole family.',
    imageUrls: ['https://picsum.photos/seed/blackx5/600/400', 'https://picsum.photos/seed/x5interior/600/400', 'https://picsum.photos/seed/x5headlight/600/400'],
    isFeatured: true,
  },
  {
    id: 'v3',
    make: 'BMW',
    model: 'M2 CS',
    year: 2020,
    price: 49500000,
    mileage: 12874,
    vin: 'WBS789...',
    engine: '3.0L Twin-Turbo I6',
    transmission: 'Manual',
    exteriorColor: 'Misano Blue Metallic',
    interiorColor: 'Black Dakota Leather/Alcantara',
    features: ['Carbon Fiber Roof', 'Adaptive M Suspension', 'M-Sport Brakes', 'Gold Wheels'],
    description: 'A future classic. This limited-edition M2 CS with a 6-speed manual transmission is a pure driver\'s car. Meticulously maintained and collector-owned.',
    imageUrls: ['https://picsum.photos/seed/bluem2/600/400', 'https://picsum.photos/seed/m2interior/600/400', 'https://picsum.photos/seed/m2spoiler/600/400'],
    isFeatured: true,
  },
  {
    id: 'v4',
    make: 'BMW',
    model: '330i M-Sport',
    year: 2023,
    price: 25000000,
    mileage: 8851,
    vin: 'WBSABC...',
    engine: '2.0L Turbo I4',
    transmission: 'Automático',
    exteriorColor: 'Brooklyn Grey',
    interiorColor: 'Tacora Red',
    features: ['M Sport Package', 'Live Cockpit Pro', 'Shadowline Trim', 'Premium Package'],
    description: 'Like-new G20 330i with the desirable M-Sport package and a striking color combination. Balance of factory warranty remaining.',
    imageUrls: ['https://picsum.photos/seed/grey330i/600/400', 'https://picsum.photos/seed/330iinterior/600/400', 'https://picsum.photos/seed/330iscreen/600/400'],
    isFeatured: false,
  },
];
