import type { Product, Vehicle } from './types';

export const products: Product[] = [
  {
    id: 'e36-bomba-freno',
    name: 'Bomba de Freno para BMW E36',
    sku: 'E36-BF-001',
    category: 'Original',
    price: 100000,
    description: 'Bomba de freno de alta precisión para BMW E36. Garantiza presión hidráulica estable y mejora la respuesta del pedal de freno. Ideal para reemplazo de piezas desgastadas.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/bomba-freno/500/500'],
  },
  {
    id: 'e36-booster',
    name: 'Booster (Servofreno) para BMW E36',
    sku: 'E36-BST-001',
    category: 'Original',
    price: 100000,
    description: 'Asistencia de frenado eficiente. Reduce el esfuerzo al frenar. Instalación directa tipo OEM. Compatible con sistema original BMW.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/booster/500/500'],
  },
  {
    id: 'e36-bomba-agua',
    name: 'Bomba de Agua para BMW E36',
    sku: 'E36-BA-001',
    category: 'Original',
    price: 100000,
    description: 'Mantiene la circulación adecuada del refrigerante. Ayuda a prevenir sobrecalentamiento del motor. Construcción resistente para larga duración. Ajuste directo para BMW E36.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/bomba-agua/500/500'],
  },
  {
    id: 'e36-volante',
    name: 'Volante para BMW E36',
    sku: 'E36-VOL-001',
    category: 'Original',
    price: 100000,
    description: 'Diseño ergonómico, compatible con sistema de dirección BMW E36. Mejora el control y la conducción. Opciones originales o deportivas.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/volante/500/500'],
  },
  {
    id: 'e36-computadora',
    name: 'Computadora (DME) para BMW E36',
    sku: 'E36-ECU-001',
    category: 'Original',
    price: 100000,
    description: 'Computadora de motor (DME) para BMW E36. Restaura el rendimiento original y la gestión electrónica de tu vehículo.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/computadora/500/500'],
  },
  {
    id: 'e36-compensadores',
    name: 'Compensadores para BMW E36',
    sku: 'E36-CMP-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Ayudan a mantener balance en el sistema mecánico. Ofrecen un funcionamiento suave y preciso. Compatible con componentes originales.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/compensadores/500/500'],
  },
  {
    id: 'e36-discos-freno',
    name: 'Discos de Freno para BMW E36',
    sku: 'E36-DF-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Alta resistencia al calor y excelente rendimiento de frenado. Material duradero y confiable, compatible con sistema original del E36.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/discos-freno/500/500'],
  },
  {
    id: 'e36-roles-empuje',
    name: 'Roles de Empuje para BMW E36',
    sku: 'E36-RE-001',
    category: 'Original',
    price: 100000,
    description: 'Reduce fricción en componentes móviles. Mejora funcionamiento del sistema. Material resistente al desgaste.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/roles-empuje/500/500'],
  },
  {
    id: 'e36-consola-central',
    name: 'Consola Central para BMW E36',
    sku: 'E36-CC-001',
    category: 'Original',
    price: 100000,
    description: 'Plástico original o de alta calidad. Ajuste perfecto al interior del E36. Mejora la estética del vehículo. Fácil instalación.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/consola-central/500/500'],
  },
  {
    id: 'e36-bomba-gasolina',
    name: 'Bomba de Gasolina para BMW E36',
    sku: 'E36-BG-001',
    category: 'Original',
    price: 100000,
    description: 'Flujo constante de combustible. Mejora el rendimiento del motor. Compatible con sistema original. Alta durabilidad.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/bomba-gasolina/500/500'],
  },
  {
    id: 'e36-cluster',
    name: 'Cluster (Panel de Instrumentos) para BMW E36',
    sku: 'E36-CLU-001',
    category: 'Usado',
    price: 100000,
    description: 'Lectura clara de velocidad, RPM y combustible. Compatible con sistema eléctrico original. Ideal para reemplazo o restauración.',
    stock: 10,
    condition: 'Usado',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/cluster/500/500'],
  },
  {
    id: 'e36-resortes',
    name: 'Resortes de Suspensión para BMW E36',
    sku: 'E36-RES-001',
    category: 'Aftermarket',
    price: 100000,
    description: 'Mantienen la altura correcta del vehículo. Mejoran estabilidad y manejo. Construcción en acero de alta resistencia.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/resortes/500/500'],
  },
  {
    id: 'e36-espejos',
    name: 'Espejos Retrovisores para BMW E36',
    sku: 'E36-ESP-001',
    category: 'Original',
    price: 100000,
    description: 'Diseño original para BMW E36. Excelente visibilidad y ajuste preciso en carrocería. Construcción resistente.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/espejos/500/500'],
  },
  {
    id: 'e36-dash',
    name: 'Dash (Tablero) para BMW E36',
    sku: 'E36-DSH-001',
    category: 'Original',
    price: 100000,
    description: 'Diseño original BMW. Mejora apariencia interior. Material resistente al calor y desgaste. Ideal para restauraciones.',
    stock: 10,
    condition: 'Nuevo',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/dash/500/500'],
  },
  {
    id: 'e36-asientos',
    name: 'Asientos para BMW E36',
    sku: 'E36-ASN-001',
    category: 'Usado',
    price: 100000,
    description: 'Comodidad y soporte ergonómico. Compatibles con rieles originales. Perfectos para restauración o reemplazo.',
    stock: 10,
    condition: 'Usado',
    compatibility: ['E36'],
    imageUrls: ['https://picsum.photos/seed/asientos/500/500'],
  },
];

export const vehicles: Vehicle[] = [];
